routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth'], function() {
    Route::get('/', 'Admin\AdminController@index')->name('stat');
    Route::get('/stat_export', 'Admin\AdminController@export')->name('stat.export');
    Route::any('faq', 'Admin\AdminController@faq')->name('faq');
	Route::resource('departments', 'Admin\DepartmentController');
	Route::resource('requests', 'Admin\RequestsController');
	Route::resource('request_priroda', 'Admin\PrirodaController');
	//Route::get('request_priroda/action/{id}', 'Admin\PrirodaController@action')->name('request_priroda.action');
	Route::resource('changes', 'Admin\ChangeController');
	Route::resource('personal', 'Admin\PersonalController');
	Route::resource('news', 'Admin\NewsController');
	Route::resource('pages', 'Admin\PagesController');
	Route::resource('instructions', 'Admin\InstructionsController');
	Route::resource('regions', 'Admin\RegionsController');
});


Route::put('admin/changes/{id}/apply', 'Admin\ChangeController@apply')->name('admin.changes.apply');
Route::get('admin/changes_stat', 'Admin\ChangeStatController@index')->name('admin.changes_stat.index');
Route::get('admin/changes_stat/{id}', 'Admin\ChangeStatController@show')->name('admin.changes_stat.show');
Route::post('admin/requests/{id}/rotate_img', 'Admin\RequestsController@rotateFiles')->name('admin.requests.rotate_img');

routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('dashboard', function() {
    if (1 == Auth::user()->id || Auth::user()->department_id) {
        return redirect('/admin');
    }

    if (null == Auth::user()->department_id) {
        return redirect('/dashboard/requests');
    }
});

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'auth'], function() {
    Route::resource('requests', 'DashboardController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'AppController@index');
Route::get('/requests/{id}/to_work', '\App\Http\Controllers\Admin\RequestsController@toWork')->name('admin.requests.to_work');
Route::get('/request/{id}', 'AppController@index');
Route::get('page', 'AppController@page');
Route::get('news', 'AppController@news');
Route::get('help', 'AppController@help');
Route::get('news-item', 'AppController@newsItem');

Route::get('point_all', 'ResourceController@point_all');
Route::get('point_orange', 'ResourceController@point_orange');
Route::get('point_green', 'ResourceController@point_green');

Route::get('/port_query/{id}', 'ResourceController@port_query');

Route::get('/requests/1/ajax_all1', 'ResourceController@ajax_all1');
Route::get('/requests/1/ajax_all2', 'ResourceController@ajax_all2');


Route::get('/requests/2/ajaxOne', 'ResourceController@ajaxOne2');
Route::get('/requests/2/ajaxTwo', 'ResourceController@ajaxTwo2');

Route::get('/requests/2/marker', 'ResourceController@marker2');

Route::get('/regions/ajax', 'ResourceController@regions');

Route::resource('requests', 'ResourceController');

Route::get('departments/{region}', 'ResourceController@getDepartmentInfoGet');
Route::post('departments', 'ResourceController@getDepartmentInfo');

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

//Route::get('/home', 'HomeController@index');

include 'admin.php';
include 'dashboard.php';

resources/views/admin/requests_priroda/edit.blade.php
@extends('admin.base')

@section('content')
    <!-- Modal -->
    <div class="modal fade" id="modal-confirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Вы уверены, что хотите удалить это фото?</h4>
                </div>
                <div class="modal-body">
                    <div id="comfirm-photo"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    <button type="button" class="btn btn-danger">Удалить</button>
                </div>
            </div>
        </div>
    </div>

    <h1>Редактировать обращение из "Нашей природы"</h1>

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    @if(Session::has('message'))
        <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
    @endif
    <form action="{{ route('admin.request_priroda.update', $priroda) }}" method="post"
          id="edit-request-form"
          enctype="multipart/form-data">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="put"/>

        <table class="table">
            <tr>
                <td width="180">Обращение</td>
                <td>
                    @if ($priroda->request)
                        <a href="{{ route('admin.requests.edit', $priroda->request) }}">{{ $priroda->request->id }}</a>
                    @endif
                </td>
            </tr>
            <tr>
                <td>Тема</td>
                <td>
                    <input type="text" class="form-control" name="subject" value="{{ $priroda->subject }}">
                </td>
            </tr>
            <tr>
                <td>Сообщение</td>
                <td>
                    <textarea name="description" class="form-control">{{ $priroda->description }}</textarea>
                </td>
            </tr>
            <tr>
                <td>Адрес</td>
                <td>
                    <input type="text" class="form-control" name="address" value="{{ $priroda->address }}">
                </td>
            </tr>
            <tr>
                <td>Геопозиция</td>
                <td>
                    <input type="text" class="form-control" name="map_point"
                           @if(isset($priroda->map_point[0]) && isset($priroda->map_point[1])) value="{{ $priroda->map_point[0] }}, {{ $priroda->map_point[1] }}"
                           @endif required>
                </td>
            </tr>
            <tr>
                <td>Заявитель</td>
                <td>
                    @if($admin)
                        <input type="text" class="form-control" name="name" value="{{ $priroda->name }}">
                    @else
                        {{ $priroda->name }}
                    @endif
                </td>
            </tr>
            <tr>
                <td>Фото</td>
                <td>
                    <div class="requset-photos">

                        @if (is_array($priroda->photo))
                            @foreach($priroda->photo as $ph)
                                <div class="photo">
                                    <a href="{{ $ph['file'] }}" rel="gallery" class="fancybox" target="_blank">
                                        <img src="{{ $ph['preview'] }}" style="width: 100px"></a>
                                    @if($admin)
                                        <button type="button"
                                                class="btn btn-xs btn-danger btn-block delete-user-photo">
                                            Удалить
                                        </button>
                                    @endif
                                </div>
                            @endforeach
                        @endif
                    </div>
                    <div id="deleted-photos"></div>
                </td>
            </tr>
            @if($priroda->participate)
                <tr class="success">
                    <td></td>
                    <td>Готов участвовать ликвидации экологического нарушения</td>
                </tr>
            @endif
            <tr>
                <td>Фото с "Нашей природы"</td>
                <td>
                    <div class="requset-photos">

                        @if (is_array($priroda->photo_admin))
                            @foreach($priroda->photo_admin as $ph)
                                <div class="photo">
                                    <a href="{{ $ph['file'] }}" rel="gallery" class="fancybox" target="_blank">
                                        <img src="{{ $ph['preview'] }}" style="width: 100px"></a>
                                    @if($admin)
                                        {{--<button type="button"--}}
                                                {{--class="btn btn-xs btn-danger btn-block delete-user-photo">--}}
                                            {{--Удалить--}}
                                        {{--</button>--}}
                                    @endif
                                </div>
                            @endforeach
                        @endif
                    </div>
                </td>
            </tr>
            <tr>
                <td>Комментарии с "Нашей природы"</td>
                <td style="font-size:80%;">
                    {!!  implode('<br />', $priroda->getCommentsPriroda()) !!}
                </td>
            </tr>
            <tr>
                <td>Комментарий в "Наша природа"</td>
                <td>
                    <textarea name="comment" rows="6" class="form-control">{{ $priroda->comment }}</textarea>
                    <small><i>уходит в "Наша природа" при подверждении администратором*</i></small>
                </td>
            </tr>
            @if ($priroda->state_id == \App\RequestPriroda::STATE_PROGRESS && $priroda->comment_admin)
                <tr>
                    <td>Сообщение от администратора</td>
                    <td>
                        {{ $priroda->comment_admin }}
                    </td>
                </tr>
            @elseif ($admin && $priroda->state_id == \App\RequestPriroda::STATE_ADMIN)
                <tr>
                    <td>Комментарий для РИК ОНФ</td>
                    <td>
                        <textarea name="comment_admin"
                                  class="form-control"
                                  onfocus="$(this).select()"
                                  style="margin-top: 5px;"
                        >{{ old('comment_admin', $priroda->comment_admin) }}</textarea>
                    </td>
                </tr>
            @endif
            <tr>
            </tr>
            <tr>
                @if (!$admin && $priroda->state_id == \App\RequestPriroda::STATE_PROGRESS)
                    <td colspan="2">
                        <button name="accept" value="1" class="btn btn-success">Подтвердить</button>
                        <button name="accept" value="0" class="btn btn-danger">Отказать</button>
                    </td>
                @elseif ($admin && $priroda->state_id == \App\RequestPriroda::STATE_ADMIN)
                    <td colspan="2">
                        <button name="accept_admin" value="1" class="btn btn-success">Подтвердить</button>
                        <button name="accept_admin" value="0" class="btn btn-danger">Отказать</button>
                    </td>
                @elseif ($priroda->state_id == \App\RequestPriroda::STATE_ADMIN)
                    <td colspan="2" class="success">На подтверждении у администратора!</td>
                @elseif ($priroda->state_id == \App\RequestPriroda::STATE_OK)
                    <td colspan="2" class="success">Обращение подтверждено!</td>
                @elseif ($priroda->state_id == \App\RequestPriroda::STATE_REPEAT)
                    <td colspan="2" class="danger">Обращение "Отправлено повторно" ({{ $priroda->date_state_repeat }})</td>
                @endif
            </tr>

            <tr>
                <td colspan="2">
                    <input type="submit" class="btn btn-primary" value="Сохранить">
                    <a href="{{ route('admin.request_priroda.index') }}" class="btn btn-secondary">Отмена</a>
                </td>
            </tr>
        </table>
    </form>

    @if($admin)
        <table class="table">
            <tr>
                <td colspan="2">
                    <form action="{{ route('admin.request_priroda.destroy', ['request' => $priroda->id]) }}" method="post">
                        {{ csrf_field() }}
                        <input type="hidden" name="_method" value="delete"/>
                        <input type="submit" class="btn btn-danger" value="Удалить"
                               onclick="return confirm('Вы уверены?');">
                    </form>
                </td>
            </tr>
        </table>
    @endif
@endsection

resources/views/admin/requests_priroda/index.blade.php
@extends('admin.base')

@section('content')
    <form action="{{ \Illuminate\Support\Facades\Request::url() }}" method="get" id="filter-form">
        @if($filtered)
            <a href="{{ route('admin.request_priroda.index') }}">&larr; Все обращения</a>
            <hr>
        @endif
        <div class="row">
            <div class="col-sm-12">
                <h1>Работа с "Нашей природой"</h1>
            </div>
        </div>
        <div class="row">
            @if($admin)
                <div class="col-sm-2">
                    <select name="region" class="form-control" id="select-region">
                        <option value=""
                                @if(!isset($filter['region']) || $filter['region'] == '') selected="selected" @endif>
                            Выбор региона
                        </option>
                        @foreach($regions as $k => $region)
                            <option value="{{ $k }}"
                                    @if(isset($filter['region']) && $filter['region'] == $k) selected="selected" @endif>{{ $region }}</option>
                        @endforeach
                    </select>
                </div>
            @endif
            <div class="col-sm-2">
                <input type="text" name="{{\App\Request::FILTER_ID}}" placeholder="Номер" class="form-control"
                       @if(isset($filter[\App\Request::FILTER_ID])) value="{{ $filter[\App\Request::FILTER_ID] }}" @endif>
            </div>
            <div class="col-sm-3">
                <input type="text" name="{{\App\Request::FILTER_NUMBER}}" placeholder="Исходный номер" class="form-control"
                       @if(isset($filter[\App\Request::FILTER_NUMBER])) value="{{ $filter[\App\Request::FILTER_NUMBER] }}" @endif>
            </div>
            {{--<div class="col-sm-2">--}}
                {{--<input type="text" name="{{\App\Request::FILTER_ZAYAV}}" placeholder="Заявитель"--}}
                       {{--class="form-control"--}}
                       {{--@if(isset($filter[\App\Request::FILTER_ZAYAV])) value="{{ $filter[\App\Request::FILTER_ZAYAV] }}" @endif>--}}
            {{--</div>--}}
        </div>
        <div class="row">
            <div class="col-md-12">
                <input style="margin-top: 10px;display:block;;width: 100%;" class=" btn btn-info" type="submit"
                       value="Поиск">
            </div>
        </div>
        <table class="table">
            <thead>
            <td width="50">Номер</td>
            <td width="100">Файлы</td>
            <td>Тема</td>
            @if($admin)
                <td>Регион</td>
            @endif
            <td>Исходный номер</td>
            <td width="170">
                <select name="state_id" id="select-status" class="form-control">
                    <option value=""
                            @if(!isset($filter['state_id']) || $filter['state_id'] == '') selected="selected" @endif>Состояние
                    </option>
                    @foreach(\App\RequestPriroda::getState() as $code => $name)
                        <option value="{{ $code }}"
                                @if(array_get($filter, 'state_id') == $code) selected="selected" @endif>{{ $name }}
                        </option>
                    @endforeach
                </select>
            </td>
            </thead>
            @foreach($prirodaRequest as $request)
                <tr>
                    <td>
                        <small class="text-nowrap">{{ $request->number }}</small>
                    </td>
                    <td>
                        @if($request->photo)
                            <a href="{{ $request->photo[0]['file'] }}" target="_blank" class="fancybox">
                                <img src="{{ $request->photo[0]['preview'] }}" style="width: 100px">
                            </a>
                        @endif
                    </td>
                    <td>
                        <small>
                            <a href="{{ route('admin.request_priroda.edit', ['request' => $request->id]) }}">{{ $request->subject }}</a>
                        </small>
                    </td>
                    @if($admin)
                        <td>
                            <small>{{ $request->region ? $request->region->name  : ''}}</small>
                        </td>
                    @endif
                    <td>
                        <small>{{ $request->request ? $request->request->id : '' }}</small>
                    </td>
                    <td>
                        <small class="text-nowrap">{{ $request->stateName() }} @if ($request->date_state_repeat)<br />({{ $request->date_state_repeat }})@endif</small>
                    </td>
                </tr>
            @endforeach
        </table>
    </form>
    <div>
        {{ $prirodaRequest->appends($filter)->links() }}
    </div>
@endsection