routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth'], function() {
    Route::get('/', 'Admin\AdminController@index')->name('stat');
    Route::get('/stat_export', 'Admin\AdminController@export')->name('stat.export');
    Route::any('faq', 'Admin\AdminController@faq')->name('faq');
	Route::resource('departments', 'Admin\DepartmentController');
	Route::resource('requests', 'Admin\RequestsController');
	Route::resource('request_priroda', 'Admin\PrirodaController');
	//Route::get('request_priroda/action/{id}', 'Admin\PrirodaController@action')->name('request_priroda.action');
	Route::resource('changes', 'Admin\ChangeController');
	Route::resource('personal', 'Admin\PersonalController');
	Route::resource('news', 'Admin\NewsController');
	Route::resource('pages', 'Admin\PagesController');
	Route::resource('instructions', 'Admin\InstructionsController');
	Route::resource('regions', 'Admin\RegionsController');
});


Route::put('admin/changes/{id}/apply', 'Admin\ChangeController@apply')->name('admin.changes.apply');
Route::get('admin/changes_stat', 'Admin\ChangeStatController@index')->name('admin.changes_stat.index');
Route::get('admin/changes_stat/{id}', 'Admin\ChangeStatController@show')->name('admin.changes_stat.show');
Route::post('admin/requests/{id}/rotate_img', 'Admin\RequestsController@rotateFiles')->name('admin.requests.rotate_img');

routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('dashboard', function() {
    if (1 == Auth::user()->id || Auth::user()->department_id) {
        return redirect('/admin');
    }

    if (null == Auth::user()->department_id) {
        return redirect('/dashboard/requests');
    }
});

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'auth'], function() {
    Route::resource('requests', 'DashboardController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'AppController@index');
Route::get('/requests/{id}/to_work', '\App\Http\Controllers\Admin\RequestsController@toWork')->name('admin.requests.to_work');
Route::get('/request/{id}', 'AppController@index');
Route::get('page', 'AppController@page');
Route::get('news', 'AppController@news');
Route::get('help', 'AppController@help');
Route::get('news-item', 'AppController@newsItem');

Route::get('point_all', 'ResourceController@point_all');
Route::get('point_orange', 'ResourceController@point_orange');
Route::get('point_green', 'ResourceController@point_green');

Route::get('/port_query/{id}', 'ResourceController@port_query');

Route::get('/requests/1/ajax_all1', 'ResourceController@ajax_all1');
Route::get('/requests/1/ajax_all2', 'ResourceController@ajax_all2');


Route::get('/requests/2/ajaxOne', 'ResourceController@ajaxOne2');
Route::get('/requests/2/ajaxTwo', 'ResourceController@ajaxTwo2');

Route::get('/requests/2/marker', 'ResourceController@marker2');

Route::get('/regions/ajax', 'ResourceController@regions');

Route::resource('requests', 'ResourceController');

Route::get('departments/{region}', 'ResourceController@getDepartmentInfoGet');
Route::post('departments', 'ResourceController@getDepartmentInfo');

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

//Route::get('/home', 'HomeController@index');

include 'admin.php';
include 'dashboard.php';

resources/views/admin/base.blade.php
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta id="token" name="token" value="{{csrf_token()}}">

    <title>Панель управления &mdash; Экологическая карта</title>

    <link href="https://fonts.googleapis.com/css?family=Open Sans:100,600" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="/js/fancybox/jquery.fancybox.css">
    <link rel="stylesheet" type="text/css" href="/css/admin.css?v={{ time() }}">
</head>
<body>
<div>
    <div class="body container">
        <div class="col-sm-3">
            <strong>
                @if (! Auth::user()->department_id)
                    Управление системой
                @else
                    {{ $department_title }}
                @endif
            </strong>

            <ul class="navigation">
                <li>
                    <a href="/">Вернуться на сайт</a>
                </li>
                <li>
                    <a href="/admin">Статистика</a>
                </li>
                <li>
                    <a href="{{ route('admin.requests.index') }}">Обращения</a>
                </li>
                <li>
                    <a href="{{ route('admin.request_priroda.index') }}">Работа с "Нашей природой"</a>
                </li>
                @if(\Auth::user()->isAdmin())
                    <li>
                        <a href="{{ route('admin.changes.index') }}">Смена статуса</a>
                    </li>
                @else
                    <li>
                        <a href="{{ route('admin.changes_stat.index') }}">Запросы на смену статуса</a>
                    </li>
                @endif
                <li>
                    <i>Структура</i>
                    <ul>
                        @if (! Auth::user()->department_id)
                            <li><a href="{{ route('admin.departments.index') }}">Отделения</a></li>
                        @endif
                        <li><a href="{{ route('admin.personal.index') }}">Сотрудники</a></li>
                        @if (! Auth::user()->department_id)
                            <li><a href="{{ route('admin.regions.index') }}">Регионы</a></li>
                        @endif
                    </ul>
                </li>
                @if(null != Auth::user() && 1 == Auth::user()->id)
                    <li>
                        <a href="{{ route('admin.news.index') }}">Новости</a>
                    </li>
                    <li>
                        <a href="{{ route('admin.pages.index') }}">Страницы</a>
                    </li>
                @endif
                @if (! Auth::user()->department_id)
                    <li>
                        <a href="{{ route('admin.instructions.index') }}">Инструкции</a>
                    </li>
                @endif
                <li>
                    <a href="{{ route('logout') }}"
                       onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();">Выйти из системы</a>

                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                    </form>
                </li>
            </ul>
        </div>
        <div class="col-sm-9">
            @yield('content')
        </div>
    </div>
</div>
<script src="https://use.fontawesome.com/1e1e181846.js"></script>
<script src="/js/jquery-1.10.1.min.js"></script>
<script src="/js/jquery.mousewheel-3.0.6.pack.js"></script>
<script src="/js/fancybox/jquery.fancybox.js" type="text/javascript"></script>
{{--<script src="/js/app.js" type="text/javascript"></script>--}}
        <!-- File upload -->
<script src="/js/fileupload/jquery.ui.widget.js"></script>
<script src="/js/fileupload/jquery.iframe-transport.js"></script>
<script src="/js/fileupload/jquery.fileupload.js"></script>

<script src="/js/admin.js?v=140219" type="text/javascript"></script>

<script>
    $(document).ready(function () {
        $('.fancybox').fancybox();
    });
</script>
</body>
</html>

resources/views/admin/index.blade.php
@extends('admin.base')

@section('content')
    <h1>Статистика</h1>
    <p style="margin-bottom: 30px">Всего обращений: <b>{{ $total }}</b>, из них:</p>

    <p class="status small" style="margin-bottom: 20px">
        <i class="fa fa-exclamation-triangle" aria-hidden="true"></i> На модерации: <b>{{ $moderate }}</b>
    </p>

    <p class="status small text-danger" style="margin-bottom: 20px">
        <i class="fa fa-info-circle" aria-hidden="true"></i> В стадии рассмотрения: <b>{{ $pending }}</b>
    </p>

    <p class="status small text-warning" style="margin-bottom: 20px">
        <i class="fa fa-hourglass" aria-hidden="true"></i> В работе: <b>{{ $work }}</b>
    </p>

    <p class="status small text-success">
        <i class="fa fa-check" aria-hidden="true"></i> Проблем решено: <b>{{ $done }}</b>
    </p>
    @if(isset($regions))
    @include('admin.rating.index')
    @endif
@endsection