routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth'], function() {
    Route::get('/', 'Admin\AdminController@index')->name('stat');
    Route::get('/stat_export', 'Admin\AdminController@export')->name('stat.export');
    Route::any('faq', 'Admin\AdminController@faq')->name('faq');
	Route::resource('departments', 'Admin\DepartmentController');
	Route::resource('requests', 'Admin\RequestsController');
	Route::resource('request_priroda', 'Admin\PrirodaController');
	//Route::get('request_priroda/action/{id}', 'Admin\PrirodaController@action')->name('request_priroda.action');
	Route::resource('changes', 'Admin\ChangeController');
	Route::resource('personal', 'Admin\PersonalController');
	Route::resource('news', 'Admin\NewsController');
	Route::resource('pages', 'Admin\PagesController');
	Route::resource('instructions', 'Admin\InstructionsController');
	Route::resource('regions', 'Admin\RegionsController');
});


Route::put('admin/changes/{id}/apply', 'Admin\ChangeController@apply')->name('admin.changes.apply');
Route::get('admin/changes_stat', 'Admin\ChangeStatController@index')->name('admin.changes_stat.index');
Route::get('admin/changes_stat/{id}', 'Admin\ChangeStatController@show')->name('admin.changes_stat.show');
Route::post('admin/requests/{id}/rotate_img', 'Admin\RequestsController@rotateFiles')->name('admin.requests.rotate_img');

routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('dashboard', function() {
    if (1 == Auth::user()->id || Auth::user()->department_id) {
        return redirect('/admin');
    }

    if (null == Auth::user()->department_id) {
        return redirect('/dashboard/requests');
    }
});

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'auth'], function() {
    Route::resource('requests', 'DashboardController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'AppController@index');
Route::get('/requests/{id}/to_work', '\App\Http\Controllers\Admin\RequestsController@toWork')->name('admin.requests.to_work');
Route::get('/request/{id}', 'AppController@index');
Route::get('page', 'AppController@page');
Route::get('news', 'AppController@news');
Route::get('help', 'AppController@help');
Route::get('news-item', 'AppController@newsItem');

Route::get('point_all', 'ResourceController@point_all');
Route::get('point_orange', 'ResourceController@point_orange');
Route::get('point_green', 'ResourceController@point_green');

Route::get('/port_query/{id}', 'ResourceController@port_query');

Route::get('/requests/1/ajax_all1', 'ResourceController@ajax_all1');
Route::get('/requests/1/ajax_all2', 'ResourceController@ajax_all2');


Route::get('/requests/2/ajaxOne', 'ResourceController@ajaxOne2');
Route::get('/requests/2/ajaxTwo', 'ResourceController@ajaxTwo2');

Route::get('/requests/2/marker', 'ResourceController@marker2');

Route::get('/regions/ajax', 'ResourceController@regions');

Route::resource('requests', 'ResourceController');

Route::get('departments/{region}', 'ResourceController@getDepartmentInfoGet');
Route::post('departments', 'ResourceController@getDepartmentInfo');

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

//Route::get('/home', 'HomeController@index');

include 'admin.php';
include 'dashboard.php';

app/Personal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Personal extends Model
{
    public $table = 'personal';

    public $fillable = [
        'department_id',
        'name',
        'position',
        'contacts',
        'email',
        'status'
    ];

    public function department()
    {
        return $this->belongsTo('App\\Department', 'department_id');
    }
}

app/Http/Controllers/Admin/PersonalController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Department;
use App\Personal;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class PersonalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $request = \App\Personal::where('id', '>', 0);
        $department_title = '';
        if (Auth::user()->department_id) {
            $request = \App\Personal::where('department_id', Auth::user()->department_id);
            $department_title = Department::find((int)Auth::user()->department_id)->region_name;
        }

        $personalList = $request->with(['department'])->orderBy('name', 'asc')->get();

        return view('admin.personal.index', [
            'personalList' => $personalList,
            'department_title' => $department_title
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.personal.create', [
            'departments' => Department::all()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $attributes = $request->all();
        $attributes['department_id'] = (int)$attributes['department_id'];
        Personal::create($attributes);

        return redirect(route('admin.personal.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $personal = Personal::find($id);

        $department_title = '';

        if (Auth::user()->department_id) {
            $department_title = Department::find((int)Auth::user()->department_id)->region_name;
        }

        return view('admin.personal.edit', [
            'personal' => $personal,
            'departments' => Department::all(),
            'department_title' => $department_title
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Personal::find($id)->update($request->all());

        return redirect(route('admin.personal.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Personal::find($id)->delete();

        return redirect(route('admin.personal.index'));
    }
}

resources/views/admin/personal/create.blade.php
@extends('admin.base')

@section('content')
    <h1>Создать сотрудника</h1>

    <form action="{{ route('admin.personal.store') }}" method="post">
        {{ csrf_field() }}

        <div class="form-group row">
            <label for="" class="col-sm-3">ФИО</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" name="name" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="" class="col-sm-3">Отделение</label>
            <div class="col-sm-9">
                <select name="department_id" class="form-control">
                    @foreach($departments as $department)
                    <option value="{{ $department->id }}">{{ $department->name }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="" class="col-sm-3">Должность</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" name="position" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="" class="col-sm-3">Контактные данные</label>
            <div class="col-sm-9">
                <textarea class="form-control" name="contacts" rows="5"></textarea>
            </div>
        </div>

        <div class="form-group row">
            <label for="" class="col-sm-3">Email для автоматических уведомлений</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" name="email">
            </div>
        </div>

        <div class="row">
            <div class="col-sm-9 col-sm-offset-3">
                <input type="submit" class="btn btn-primary btn-lg" value="Создать сотрудника">
                <a href="{{ route('admin.personal.index') }}" class="btn btn-secondary btn-lg" >Отмена</a>
            </div>
        </div>
    </form>
@endsection

resources/views/admin/personal/edit.blade.php
@extends('admin.base')

@section('content')
    <h1>Редактировать сотрудника</h1>

    <form action="{{ route('admin.personal.update', ['personal' => $personal->id]) }}" method="post">
        {{ csrf_field() }}
        <input type="hidden" name="_method" value="put" />

        <div class="form-group row">
            <label for="" class="col-sm-3">ФИО</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" name="name" value="{{ old('name', $personal->name) }}" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="" class="col-sm-3">Отделение</label>
            <div class="col-sm-9">
                <select name="department_id" class="form-control">
                    @foreach($departments as $department)
                    <option value="{{ $department->id }}" @if($personal->department_id == $department->id) selected="selected" @endif>{{ $department->name }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="form-group row">
            <label for="" class="col-sm-3">Должность</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" name="position" value="{{ old('position', $personal->position) }}" required>
            </div>
        </div>

        <div class="form-group row">
            <label for="" class="col-sm-3">Контактные данные</label>
            <div class="col-sm-9">
                <textarea class="form-control" name="contacts" rows="5">{{ old('contacts', $personal->contacts) }}</textarea>
            </div>
        </div>

        <div class="form-group row">
            <label for="" class="col-sm-3">Email для автоматических уведомлений</label>
            <div class="col-sm-9">
                <input type="text" class="form-control" name="email" value="{{ old('email', $personal->email) }}">
            </div>
        </div>

        <div class="row">
            <div class="col-sm-9 col-sm-offset-3">
                <input type="submit" class="btn btn-primary" value="Редактировать сотрудника">
                <a href="{{ route('admin.personal.index') }}" class="btn btn-secondary" >Отмена</a>
            </div>
        </div>
    </form>

    <div class="row">
        <div class="col-sm-9 col-sm-offset-3" style="margin-top: 1em;">
            <form action="{{ route('admin.personal.destroy', ['request' => $personal->id]) }}" method="post">
                {{ csrf_field() }}
                <input type="hidden" name="_method" value="delete" />

                <input type="submit" class="btn btn-danger" value="Удалить" onclick="return confirm('Вы уверены?');">
            </form>
        </div>
    </div>
@endsection

resources/views/admin/personal/index.blade.php
@extends('admin.base')

@section('content')
    <h1>Сотрудники</h1>

    <a class="btn btn-primary" href="{{ route('admin.personal.create') }}">Создать сотрудника</a>

    <form class="pull-right">
        <input class="form-control" type="text" placeholder="Поиск" name="search">
    </form>

    <table class="table" style="margin-top: .75em;">
        <thead>
        <td>ФИО</td>
        <td>Отделение</td>
        <td>Должность</td>
        <td>Уведомления</td>
        </thead>
        @forelse($personalList as $personal)
            <tr>
                <td>
                    <a href="{{ route('admin.personal.edit', ['personal' => $personal->id]) }}">{{ $personal->name }}</a>
                </td>
                <td>
                    {{ isset($personal->department) ? $personal->department->name : '---' }}
                </td>
                <td>
                    {{ $personal->position }}
                </td>
                <td>
                    {{ '' !== $personal->email ? 'Включены' : 'Email не указан' }}
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="3">
                    <i>Нет активных сотрудников</i>
                </td>
            </tr>
        @endforelse
    </table>
@endsection