routes/admin.php
<?php

use Illuminate\Support\Facades\Route;

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth'], function() {
    Route::get('/', 'Admin\AdminController@index')->name('stat');
    Route::get('/stat_export', 'Admin\AdminController@export')->name('stat.export');
    Route::any('faq', 'Admin\AdminController@faq')->name('faq');
	Route::resource('departments', 'Admin\DepartmentController');
	Route::resource('requests', 'Admin\RequestsController');
	Route::resource('request_priroda', 'Admin\PrirodaController');
	//Route::get('request_priroda/action/{id}', 'Admin\PrirodaController@action')->name('request_priroda.action');
	Route::resource('changes', 'Admin\ChangeController');
	Route::resource('personal', 'Admin\PersonalController');
	Route::resource('news', 'Admin\NewsController');
	Route::resource('pages', 'Admin\PagesController');
	Route::resource('instructions', 'Admin\InstructionsController');
	Route::resource('regions', 'Admin\RegionsController');
});


Route::put('admin/changes/{id}/apply', 'Admin\ChangeController@apply')->name('admin.changes.apply');
Route::get('admin/changes_stat', 'Admin\ChangeStatController@index')->name('admin.changes_stat.index');
Route::get('admin/changes_stat/{id}', 'Admin\ChangeStatController@show')->name('admin.changes_stat.show');
Route::post('admin/requests/{id}/rotate_img', 'Admin\RequestsController@rotateFiles')->name('admin.requests.rotate_img');

routes/dashboard.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('dashboard', function() {
    if (1 == Auth::user()->id || Auth::user()->department_id) {
        return redirect('/admin');
    }

    if (null == Auth::user()->department_id) {
        return redirect('/dashboard/requests');
    }
});

Route::group(['prefix' => 'dashboard', 'as' => 'dashboard.', 'middleware' => 'auth'], function() {
    Route::resource('requests', 'DashboardController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Route::get('/', 'AppController@index');
Route::get('/requests/{id}/to_work', '\App\Http\Controllers\Admin\RequestsController@toWork')->name('admin.requests.to_work');
Route::get('/request/{id}', 'AppController@index');
Route::get('page', 'AppController@page');
Route::get('news', 'AppController@news');
Route::get('help', 'AppController@help');
Route::get('news-item', 'AppController@newsItem');

Route::get('point_all', 'ResourceController@point_all');
Route::get('point_orange', 'ResourceController@point_orange');
Route::get('point_green', 'ResourceController@point_green');

Route::get('/port_query/{id}', 'ResourceController@port_query');

Route::get('/requests/1/ajax_all1', 'ResourceController@ajax_all1');
Route::get('/requests/1/ajax_all2', 'ResourceController@ajax_all2');


Route::get('/requests/2/ajaxOne', 'ResourceController@ajaxOne2');
Route::get('/requests/2/ajaxTwo', 'ResourceController@ajaxTwo2');

Route::get('/requests/2/marker', 'ResourceController@marker2');

Route::get('/regions/ajax', 'ResourceController@regions');

Route::resource('requests', 'ResourceController');

Route::get('departments/{region}', 'ResourceController@getDepartmentInfoGet');
Route::post('departments', 'ResourceController@getDepartmentInfo');

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('login', 'Auth\LoginController@login');
$this->post('logout', 'Auth\LoginController@logout')->name('logout');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');

//Route::get('/home', 'HomeController@index');

include 'admin.php';
include 'dashboard.php';

app/Request.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Request extends Model
{
//    protected $table = 'requests_test';

    public $incrementing = false;

    const STATUS_MODERATE = 0;
    const STATUS_RASSMOTRENIE = 1;
    const STATUS_IN_WORK = 2;
    const STATUS_SOLVE = 3;

    const FILTER_ID = 'search';
    const FILTER_ZAYAV = 'search_zayav';
    const FILTER_EMAIL = 'search_email';
    const FILTER_PHONE = 'search_phone';
    const FILTER_NUMBER = 'search_number';

    /**
     * Атрибуты, которые должны быть преобразованы в даты.
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
        'priroda_date'
    ];

    public $fillable = [
        'id',
        'subject',
        'address',
        'description',
        'map_point',
        'address',
        'name',
        'phone',
        'email',
        'status',
        'comment',
        'region_name',
        'user_id',
        'region_id',
        'participate',
        'youtube',
        'photo',
        'photo_admin',
        'priroda_id',
        'priroda_date'
    ];

    /**
     * @return string
     * @throws \Exception
     */
    public static function generateId()
    {
        $out = date('ymd') . '-' . random_int(100, 999);

        if (Request::find($out)) {
            return self::generateId();
        }
        return $out;
    }

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function region()
    {
        return $this->belongsTo('App\Region', 'region_id', 'region_id');
    }

    public function priroda()
    {
        return $this->belongsTo(RequestPriroda::class, 'priroda_id', 'priroda_id');
    }

    private function is_serialized($data)
    {
        // if it isn't a string, it isn't serialized
        if (!is_string($data))
            return false;
        $data = trim($data);
        if ('N;' == $data)
            return true;
        if (!preg_match('/^([adObis]):/', $data, $badions))
            return false;
        switch ($badions[1]) {
            case 'a' :
            case 'O' :
            case 's' :
                if (preg_match("/^{$badions[1]}:[0-9]+:.*[;}]\$/s", $data))
                    return true;
                break;
            case 'b' :
            case 'i' :
            case 'd' :
                if (preg_match("/^{$badions[1]}:[0-9.E-]+;\$/", $data))
                    return true;
                break;
        }
        return false;
    }

    public function getPhotoAdminPreviewAttribute()
    {
        if ($this->is_serialized($this->attributes['photo_admin'])) {
            $photo_preview = unserialize($this->attributes['photo_admin']);
        } else {
            $photo_preview = $this->attributes['photo_admin'];
        }

        $result = [];
        if (is_array($photo_preview)) {
            foreach ($photo_preview as $preview) {
                $this->generatePreview($result, $preview);
            }
        } else {
            $this->generatePreview($result, $photo_preview);
        }

        if (count($result) === 1 && isset($result[0]['file']) && $result[0]['file'] == '') {
            return null;
        }

        return $result;
    }

    public function getPhotoPreviewAttribute()
    {
        if ($this->is_serialized($this->attributes['photo'])) {
            $photo_preview = unserialize($this->attributes['photo']);
        } else {
            $photo_preview = $this->attributes['photo'];
        }
        $result = [];
        if (is_array($photo_preview)) {
            foreach ($photo_preview as $preview) {
                $this->generatePreview($result, $preview);
            }
        } else {
            $this->generatePreview($result, $photo_preview);
        }

        if (count($result) === 1 && isset($result[0]['file']) && $result[0]['file'] == '') {
            return null;
        }
        return $result;
    }

    /**
     * @param $result
     * @param $preview
     * @return array
     * @throws \ImagickException | \Exception
     */
    private function generatePreview(&$result, $preview)
    {
        $path = public_path() . $preview;
        $path_preview = $path . '.preview.jpg';
        if (!file_exists($path)) {

            $result[] = [
                'path' => $path,
                'file' => $preview,
                'preview' => $preview
            ];
            return $result;
        }

        if (file_exists($path_preview)) {
            $result[] = [
                'path' => $path,
                'file' => $preview,
                'preview' => $preview . '.preview.jpg'
            ];
            return $result;
        }

        if (stripos($path, '.pdf')) {
            try {
                /** @var \Imagick $imagick */
                @$imagick = new \Imagick($path . '[0]'); // 0 specifies the first page of the pdf
                @$imagick->setImageFormat('jpg'); // set the format of the output image
                @$imagick->setImageAlphaChannel(\Imagick::VIRTUALPIXELMETHOD_WHITE);
                @$imagick->setCompressionQuality(100);
                @$imagick->writeImage($path_preview);
            } catch (\Exception $e) {}
        }
        if (
            stripos($path, '.jpg') ||
            stripos($path, '.jpeg') ||
            stripos($path, '.png') ||
            stripos($path, '.gif')

        ) {
            try {
                /** @var \Imagick $imagick */
                @$imagick = new \Imagick($path . '[0]'); // 0 specifies the first page of the pdf
                @$imagick->setImageFormat('jpg'); // set the format of the output image
                @$imagick->scaleImage(100, 0);
                @$imagick->writeImage($path_preview);
            } catch (\Exception $e) {}
        }

        if (file_exists($path_preview)) {
            $result[] = [
                'path' => $path,
                'file' => $preview,
                'preview' => $preview . '.preview.jpg'
            ];

        } else {
            $result[] = [
                'path' => $path,
                'file' => $preview,
                'preview' => $preview
            ];
        }

        return $result;
    }

    public function hasStatusSendInPriroda()
    {
        return in_array($this->status, [Request::STATUS_RASSMOTRENIE, Request::STATUS_IN_WORK]);
    }

    /**
     * @return mixed
     */
    public function uuid()
    {
        return str_replace('{ID}', $this->id, '00{ID}0-0000-0000-000000000000');
    }

    /**
     * @return mixed
     */
    public function mapPoint()
    {
        if ($this->is_serialized($this->attributes['map_point'])) {
            $map_point = unserialize($this->attributes['map_point']);
        } else {
            $map_point = $this->attributes['map_point'];
        }

        return $map_point;
    }

    /**
     * @return null
     */
    public function latitude()
    {
        $map_point = $this->mapPoint();
        return isset($map_point[0]) ? $map_point[0] : null;
    }

    /**
     * @return null
     */
    public function longitude()
    {
        $map_point = $this->mapPoint();
        return isset($map_point[1]) ? $map_point[1] : null;
    }

    public function attachments()
    {
        $files = [];
        $photo_preview = $this->photo_preview;

        if (is_array($photo_preview) && isset($photo_preview['file'])) {
            $photo_preview = [$this->photo_preview];
        }

        if ($photo_preview) {
            foreach($photo_preview as $photo) {
                if (file_exists($photo['path'])) {
                    $files[] = [
                        'name'     => 'file',
                        'contents' => fopen($photo['path'], 'r'),
                        'filename' => basename($photo['path'])
                    ];
                }
            }
        }

        return $files;
    }

    /**
     * Выставляем статус подтверждено и перекидываем фото и комментарии осталвенные модераторами из Нашей природы
     * @param RequestPriroda $priroda
     * @return bool
     */
    public function setStatusSolved(RequestPriroda $priroda)
    {
        @$photo_request = unserialize($this->photo_admin);
        // Собираем все старые фото и загружаем к ним новые
        $photo_request  = is_array($photo_request) ? $photo_request : [];
        $photo_priroda  = is_array($priroda->photo_admin) ? array_pluck($priroda->photo_admin, 'file') : [];
        $photos         = array_merge($photo_request, $photo_priroda);

        $this->comment     = implode(PHP_EOL, $priroda->getCommentsPriroda(true));
        $this->photo_admin = serialize(array_unique($photos));
        $this->status      = Request::STATUS_SOLVE;
        return $this->save();
    }
}

app/Http/Controllers/Admin/ChangeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\RequestChange;
use App\User;
use Validator;
use App\Department;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ChangeController extends Controller
{
    public function index(Request $request)
    {
        $filtered = false;
        $requests = \App\Request::
        join('request_change', 'requests.id', '=', 'request_change.request_id')
            ->where('requests.created_at', '>', 0)
            ->where('request_change.request_status', '=', 0);

        /**
         * Filter status
         */
        $filter = $request->all();
        /**
         * Filter region
         */
        if (isset($filter['region']) && $filter['region'] !== '') {
            $requests = $requests->where('requests.region_id', '=', $request->input('region'));
            $filtered = true;
        }
        /**
         * Filter search
         */
        if (isset($filter['search']) && $filter['search'] !== '') {
            $requests = $requests->where('requests.id', 'LIKE', '%' . $filter['search'] . '%');
            $filtered = true;
        }

        $department_title = '';
        if (Auth::user()->department_id) {
            $department = Department::find((int)Auth::user()->department_id);
            $requests = $requests->where('requests.region_name', $department->region_name);
            $department_title = $department->region_name;
        }

        $requests = $requests->orderBy('request_change.created_at', 'asc')->paginate(10);

        $var = $requests;

        foreach ($var as $key => $value) {
            $photos = @unserialize($value['photo']);
            $var[$key]['photo'] = (!empty($photos)) ? array_values($photos)[0] : '';
        }

        foreach (\App\Request::orderBy('region_name', 'ASC')->get() as $request) {
            $regions[$request->region_id] = $request->region_name;
        }
        return view('admin.changes.index', [
            'requests' => $var,
            'department_title' => $department_title,
            'admin' => (Auth::user()->department_id) ? false : true,
            'regions' => $regions,
            'filter' => $filter,
            'filtered' => $filtered
        ]);
    }

    public function show($id)
    {
        $request = \App\Request::find($id);

        return view('admin.changes.show', [
            'request' => $request,
            'admin' => (Auth::user()->department_id) ? false : true
        ]);
    }

    public function update()
    {
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        /** @var RequestChange $requestObject */
        $requestObject = RequestChange::find($id);

        $requestObject->photo = @unserialize($requestObject->request()->first()->photo);
        $requestObject->photo_admin = (isset($requestObject->photo_admin)) ? @unserialize($requestObject->photo_admin) : '';

        $department_title = '';
        $requestObject->map_point = @unserialize($requestObject->request()->first()->map_point);


        if (Auth::user()->department_id) {
            $department_title = Department::find((int)Auth::user()->department_id)->region_name;
        }

        return view('admin.changes.edit', [
            'request' => $requestObject,
            'department_title' => $department_title,
            'admin' => (Auth::user()->department_id) ? false : true
        ]);
    }

    public function apply(Request $request, $id)
    {
        $resolution = $request->get('resolution');

        /** @var RequestChange $rejectChange */
        $rejectChange = RequestChange::find($id);
        $rejectChange->reason = $request->get('reason');
        if ($resolution === 'apply') {
            $rejectChange->apply();
        } else {
            $rejectChange->reject();
        }

        return redirect(route('admin.changes.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $requestObject = \App\Request::where('id', $id)->first();
        $requestObject->delete();

        return redirect(route('admin.requests.index'));
    }
}

resources/views/admin/changes/edit.blade.php
@extends('admin.base')

@section('content')
        <!-- Modal -->
<div class="modal fade" id="modal-confirm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Вы уверены, что хотите удалить это фото?</h4>
            </div>
            <div class="modal-body">
                <div id="comfirm-photo"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                <button type="button" class="btn btn-danger">Удалить</button>
            </div>
        </div>
    </div>
</div>

<h1>Редактировать обращение</h1>

@if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('admin.changes.apply',['id' => $request->id]) }}" method="POST" id="edit-request-form"
      enctype="multipart/form-data">
    {{ csrf_field() }}
    <input type="hidden" name="_method" value="put"/>

    <table class="table">
        <tr>
            <td width="180">#</td>
            <td>{{ $request->request()->first()->id }}</td>
        </tr>
        <tr>
            <td>Тема</td>
            <td>
                {{ $request->request()->first()->subject }}
            </td>
        </tr>
        <tr>
            <td>Сообщение</td>
            <td>
                {{ $request->request()->first()->description }}
            </td>
        </tr>
        <tr>
            <td>Адрес</td>
            <td>
                {{ $request->request()->first()->address }}
            </td>
        </tr>
        <tr>
            <td>Геопозиция</td>
            <td>
                {{ $request->map_point[0] }}, {{ $request->map_point[1] }}
            </td>
        </tr>
        <tr>
            <td>Заявитель</td>
            <td>
                {{ $request->request()->first()->name }}
            </td>
        </tr>
        <tr>
            <td>Телефон</td>
            <td>
                {{ $request->request()->first()->phone }}
            </td>
        </tr>
        <tr>
            <td>E-mail</td>
            <td>
                {{ $request->request()->first()->email }}
            </td>
        </tr>
        <tr>
            <td>Фото</td>
            <td>
                <div class="requset-photos">
                    @if (is_array($request->request()->first()->photo_preview))
                        @if(isset($request->request()->first()->photo_preview['file']))
                            <div class="photo">
                                <a href="{{ $request->photo_preview['file'] }}" rel="gallery" class="fancybox"
                                   target="_blank">
                                    <img src="{{ $request->photo_preview['preview'] }}" style="width: 100px"></a>
                            </div>
                        @else
                            @foreach($request->request()->first()->photo_preview as $ph)
                                <div class="photo">
                                    <a href="{{ $ph['file'] }}" rel="gallery" class="fancybox" target="_blank">
                                        <img src="{{ $ph['preview'] }}" style="width: 100px"></a>
                                </div>
                            @endforeach
                        @endif
                    @endif
                </div>
                <div id="deleted-photos"></div>
            </td>
        </tr>
        @if($request->participate)
            <tr class="success">

                <td colspan="2">Готов участвовать ликвидации экологического нарушения</td>
            </tr>
        @endif
        <tr>
            <td>Комментарий</td>
            <td>
                {{ $request->request()->first()->comment }}
            </td>
        </tr>
        <tr>
            <td>Загрузить фотографии</td>
            <td>
                <div id="uploaded" class="uploaded-photos">
                    @if (is_array($request->request()->first()->photo_admin_preview))
                        @if(isset($request->request()->first()->photo_admin_preview['file']))
                            <div class="uploaded-photo">
                                <div class="preview">
                                    <a href="{{ $request->request()->first()->photo_admin_preview['file'] }}"
                                       rel="gallery_admin" class="fancybox" target="_blank">
                                        <img src="{{ $request->request()->first()->photo_admin_preview['preview'] }}">
                                    </a>
                                </div>
                                <button type="button" class="btn btn-xs btn-block btn-danger delete-file">Удалить</button>
                            </div>
                        @else
                            @foreach($request->request()->first()->photo_admin_preview as $ph)
                                <div class="uploaded-photo">
                                    <div class="preview">
                                        <a href="{{ $ph['file'] }}" rel="gallery_admin" class="fancybox"
                                           target="_blank">
                                            <img src="{{ $ph['preview'] }}">
                                        </a>
                                    </div>
                                    <button type="button" class="btn btn-xs btn-block btn-danger delete-file">Удалить
                                    </button>
                                </div>
                            @endforeach
                        @endif
                    @endif
                </div>
                <hr>
                <div id="request-photos"></div>
                <div class="progress">
                    <div class="progress-bar progress-bar-success p
                    rogress-bar-striped active" role="progressbar"
                         aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width:0%"></div>
                </div>
                <div class="form-group">
                    <input type="file" name="files[]" id="fileupload" multiple style="display: none">
                    <button type="button" class="btn btn-default" id="upload-photos">Выбрать файлы</button>
                </div>
            </td>
        </tr>
        <tr>
            <td>Cсылка на свалку</td>
            <td>
                <a target="_blank" href="{{route('admin.requests.edit',['id'=>$request->request()->first()->id])}}">Перейти</a>
            </td>
        </tr>
        <td>Текущий статус</td>
        <td>
            @php
            switch($request->request()->first()->status){
            case 0 : echo "На модерации"; break;
            case 1 : echo "На рассмотрении"; break;
            case 2 : echo "В работе"; break;
            case 3 : echo "Проблема решена"; break;
            }
            @endphp
        </td>
        </tr>

        <tr>
            <td>Запрос на смену статуса</td>
            <td>
                @php
                switch($request->old_request_status){
                case 0 : echo "На модерации"; break;
                case 1 : echo "На рассмотрении"; break;
                case 2 : echo "В работе"; break;
                case 3 : echo "Проблема решена"; break;
                }
                @endphp ->
                @php
                switch($request->new_request_status){
                case 0 : echo "На модерации"; break;
                case 1 : echo "На рассмотрении"; break;
                case 2 : echo "В работе"; break;
                case 3 : echo "Проблема решена"; break;
                }
                @endphp
            </td>
        </tr>
        <tr>
            <td>Комментарий к резолюции</td>
            <td>
                <textarea style="width: 100%;height: 200px;" name="reason"></textarea>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit" name="resolution" value="apply" class="btn btn-success">Принять</button>
                <button type="submit" name="resolution" value="reject" class="btn btn-danger">Отклонить</button>
                <a href="{{ route('admin.changes.index') }}" class="btn btn-secondary">Отмена</a>
            </td>
        </tr>
    </table>
</form>

@if(!Auth::user()->department_id)
    <table class="table">
        <tr>
            <td colspan="2">
                <form action="{{ route('admin.changes.destroy', ['change' => $request->id]) }}" method="post">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="delete"/>
                    <input type="submit" class="btn btn-danger" value="Удалить"
                           onclick="return confirm('Вы уверены?');">
                </form>
            </td>
        </tr>
    </table>
@endif
@endsection

resources/views/admin/changes/index.blade.php
@extends('admin.base')

@section('content')
    <form action="{{ \Illuminate\Support\Facades\Request::url() }}" method="get" id="filter-form">
        @if($filtered)
            <a href="/admin/requests">&larr; Все обращения</a>
            <hr>

        @endif
        <div class="row">
            <div class="col-sm-6">
                <h1>Смена статуса</h1>
            </div>
            @if($admin)
                <div class="col-sm-3">
                    <select name="region" class="form-control" id="select-region">
                        <option value=""
                                @if(!isset($filter['region']) || $filter['region'] == '') selected="selected" @endif>
                            Выбор региона
                        </option>
                        @foreach($regions as $k => $region)
                            <option value="{{ $k }}"
                                    @if(isset($filter['region']) && $filter['region'] == $k) selected="selected" @endif>{{ $region }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="col-sm-3">
                    <input type="text" name="search" placeholder="Поиск обращения" class="form-control"
                           @if(isset($filter['search'])) value="{{ $filter['search'] }}" @endif>
                </div>
            @endif
        </div>
        <table class="table">
            <thead>
            <td width="50">#</td>
            <td width="100">Файлы</td>
            <td>Тема</td>
            @if($admin)
                <td>Регион</td>@endif
            <td>Заявитель</td>
            <td width="170">
                <select name="status" id="select-status" class="form-control">
                    <option value=""
                            @if(!isset($filter['status']) || $filter['status'] == '') selected="selected" @endif>Cтатус
                    </option>
                    <option value="0"
                            @if(isset($filter['status']) && $filter['status'] == '0') selected="selected" @endif>На
                        модерации
                    </option>
                    <option value="1"
                            @if(isset($filter['status']) && $filter['status'] == '1') selected="selected" @endif>На
                        рассмотрении
                    </option>
                    <option value="2"
                            @if(isset($filter['status']) && $filter['status'] == '2') selected="selected" @endif>В
                        работе
                    </option>
                    <option value="3"
                            @if(isset($filter['status']) && $filter['status'] == '3') selected="selected" @endif>
                        Проблема решена
                    </option>
                </select>
            </td>
            </thead>
            @foreach($requests as $request)
                <tr>
                    <td>
                        <small class="text-nowrap">{{ $request->request_id }}</small>
                    </td>
                    <td>
                        @if($request->photo_preview[0]['file']!=='')
                            <a href="{{ $request->photo_preview[0]['file'] }}" target="_blank" class="fancybox">
                                <img src="{{ $request->photo_preview[0]['preview'] }}" style="width: 100px">
                            </a>
                        @endif
                    </td>
                    <td>
                        <small>
                            <a href="{{ route('admin.changes.edit', ['change' => $request->id]) }}">{{ $request->subject }}</a>
                        </small>
                    </td>
                    @if($admin)
                        <td>
                            <small>{{ $request->region_name }}</small>
                        </td>@endif
                    <td>
                        <small>{{ $request->name }}</small>
                    </td>
                    <td>
                        <small class="text-nowrap">
                            @php
                            switch ($request->status) {
                            case 0:
                            echo 'На модерации';
                            break;
                            case 1:
                            echo 'На рассмотрении';
                            break;
                            case 2:
                            echo 'В работе';
                            break;
                            case 3:
                            echo 'Проблема решена';
                            break;
                            }
                            @endphp
                        </small>
                    </td>
                </tr>
            @endforeach
        </table>
    </form>
    <div>
        {{ $requests->appends($filter)->links() }}
    </div>
@endsection